### ISSUE TITLE
Version 0.1 Roadmap

### ISSUE THREAD

**Issue by frreiss** [frreiss/text-extensions-for-pandas#1]
This issue holds the main checklist of TODO items for the first release of this project.

**When an item is completed, please check off the item and add a link to the relevant pull request or commit.**

### Build/CI

- [ ] Set up Travis CI for Github repo
- [ ] Auto-run regression tests for pull requests
- [ ] Scripts and configs to create pip package
- [ ] Top-level hooks for `pytest`
- [ ] Scripts to generate API documentation from docstrings
- [ ] Web site for API documentation

### Features

- [ ] Implement all required hooks for ExtensionArray types
   - [ ] CharSpanArray
   - [ ] TokenSpanArray
   - [ ] TensorArray
- [ ] Implement key elements of spanner algebra
   - *List TBD*
- [ ] Implement key Gremlin steps and predicates
   - *List TBD*

### Regression Tests

- [ ] gremlin
	- [ ] predicate
	   - [ ] `base.py`
	   - *Other files TBD*
	- [ ] traversal
	   - [ ] `aggregate.py`
	   - [ ] `base.py`
	   - [ ] `constant.py`
	   - [ ] `filter.py`
	   - [ ] `move.py`
	   - [ ] `recurse.py`
	   - [ ] `underscore.py`
	- [ ] `convert.py`
- [ ] spanner
   - *Files TBD*
- [ ] array
   - [ ] `char_span.py`
   - [ ] `token_span.py`
- [ ] `util.py`
- [ ] Verify that API docs generate without errors
 

### Documentation

- [ ] Finish Person use case notebook
- [ ] Create getting started guide

### Refactoring

- [ ] Move spanner algebra code to multiple files under `text_extensions_for_pandas/spanner` 
- [ ] Move ExtenionArray types to `text_extensions_for_pandas/array`
